apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['sh', '-c']
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done;']
    - name: init-myservice2
      image: busybox
      command: ['sh', '-c']
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice2; sleep 2; done;']
  containers:
  - name: my-container
    image: busybox
    ports:
    - containerPort: 80
    command: ["sh", "-c"]
    args: ["while true; do echo Hello Kubernetes!; sleep 10; done"]
  tolerations:
  - key: "gpu.enabled"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 120
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: NotIn
            values:
            - ssd 
            - hhd
          - key: cpu
            operator: DoesNotExist
        - matchExpressions:
          - key: region
            operator: In
            values:
            - us-west-1
